# Generated by Django 5.1 on 2024-08-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_song_user_birthdate_playlist_playlistsong_history_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedsong',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='likedsong',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
