# Generated by Django 5.1 on 2024-09-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_likedsong_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
